### PR TITLE
Increased min char count and disallowed .

### PR DESCRIPTION
**Pull request by Oymate**

### CODE REVIEW

**Comment by mm-crj** [comment]
What is that you are trying to do [here](https://github.com/mm-crj/bn-wiki-scraper/pull/2/commits/cac01728f05977dbeda55f6e82c70c9e2e6f3b7d)? How does adding '.' to `disallowed symbols` help? In my opinion, it will at least strip all the abbreviations of the dots in between and make it impossible to detect abbreviations by using the regex.

**Comment by Oymate** [comment]
There was a lot of incomplete sentences ending with '.', hence that decision but it maybe reverted if you want.

**Comment by mm-crj** [comment]
> There was a lot of incomplete sentences ending with '.', hence that decision but it maybe reverted if you want.

No no, I am not saying its a bad thing. I just want to understand what you are trying to achieve.
So where are these sentences in the wiki dump? Can you give some examples? Because Bengali sentences usually end with '। '
not a dot.

**Comment by Oymate** [comment]
Oh, in wiki.bn.txt

The sentences from first 30-100 ending with '.' is incomplete, hence I thought disallowing this would help a lot. Plus abbreviation is not a major part of Bangla and removing it would help in extraction.

I am following the hindi pull request as well to make these changes.

Side ques: how to see wiki.bn.txt from CL in docker? Nano isn't working great.

**Pull request closed without merging**
